name: Build and deploy Doxygen docs

on:
  push:
    branches: [ "main", "feature/docs-ci" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up packages
      run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

    - name: Generate Doxygen docs
      run: doxygen Doxyfile

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
